#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


python manage.py sync_cassandra

python << END

from cassandra.auth import PlainTextAuthProvider
from cassandra.cluster import Cluster

print("CREATING INDEX IN CASSANDRA TABLE")

auth_provider = PlainTextAuthProvider(username="cassandra", password="cassandra")

cluster = Cluster(["cassandra"], auth_provider=auth_provider)
session = cluster.connect()
session.execute(
    """CREATE CUSTOM INDEX IF NOT EXISTS idx_content ON db.message (content)
USING 'org.apache.cassandra.index.sasi.SASIIndex'
WITH OPTIONS = {
'mode': 'CONTAINS',
'analyzer_class': 'org.apache.cassandra.index.sasi.analyzer.NonTokenizingAnalyzer',
'case_sensitive': 'false'};
"""
)

END

>&2 echo 'Finished creating custom index!'

uvicorn config.asgi:application --host 0.0.0.0 --reload --reload-include '*.html'
