version: '3'
 
services:
  redis:
    image: redis:6
    ports:
      - "6379:6379"
  web:
    container_name: chatApp
    build: .
    command: python chatApp/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/web
    ports:
      - "8000:8000"
    depends_on:
      - redis