version: '3'

volumes:
  local_cassandra_data: {}

services:
  redis:
    restart: always
    image: redis:6
    container_name: local_redis
    ports:
      - "6379:6379"
  cassandra:
    restart: always
    image: cassandra:4.1
    container_name: local_cassandra
    ports:
      - "9042:9042"
    volumes:
      - local_cassandra_data:/var/lib/cassandra:Z
      - ./cassandra_config/cassandra.yaml:/etc/cassandra/cassandra.yaml:z
  django:
    platform: linux/amd64
    restart: always
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: mariuscaptari/django
    container_name: local_django
    depends_on:
      - cassandra
      - redis
    env_file:
      - ./.envs/.local/.django
    ports:
      - "8000:8000"
    volumes:
      - .:/app:z
    command: /start
  frontend:
    platform: linux/amd64
    restart: always
    command: npm start
    image: mariuscaptari/frontend
    container_name: local_frontend
    build:
      context: .
      dockerfile: ./compose/local/frontend/Dockerfile
    ports:
      - "3000:3000"
    stdin_open: true
    depends_on:
      - django
    volumes:
      - ./frontend:/app/:z
