version: '3'

volumes:
  chat_app_local_cassandra_data: {}

services:
  redis:
    restart: always
    image: redis:6
    container_name: chat_app_local_redis
    ports:
      - "6379:6379"
  cassandra:
    restart: always
    image: cassandra:4.1
    container_name: chat_app_local_cassandra
    ports:
      - "9042:9042"
    volumes:
      - chat_app_local_cassandra_data:/var/lib/cassandra:Z
      - ./cassandra.yaml:/etc/cassandra/cassandra.yaml:z
  django:
    restart: always
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: chat_app_local_django
    container_name: chat_app_local_django
    platform: linux/x86_64
    depends_on:
      - cassandra
      - redis
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start

  frontend:
    restart: always
    command : npm start
    container_name: front
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    stdin_open: true
    depends_on:
      - django
    networks:
       - app-net
    volumes:
      - ./frontend:/app/frontend
networks:
  default:
    name: default_network
    driver: bridge
