###########################
# Deployment
###########################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: django
  labels:
    app: django
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
        - name: django
          image: mariuscaptari/django
          args:
            - /start
          envFrom:
            - configMapRef:
                name: django-config
          ports:
            - containerPort: 8000

---
###########################
# Cluster IP Service
###########################
apiVersion: v1
kind: Service
metadata:
  name: django
spec:
  type: ClusterIP
  selector:
    app: django
  ports:
    - port: 8000
      targetPort: 8000
---
###########################
# Config Map
###########################
apiVersion: v1
kind: ConfigMap
metadata:
  name: django-config
data:
  REDIS_HOST: redis
  REDIS_PORT: "6379"
  CASSANDRA_HOST: cassandra.default.svc.cluster.local
  CASSANDRA_USER: "cassandra"
  CASSANDRA_PASSWORD: "cassandra"
