apiVersion: v1
kind: ConfigMap
metadata:
  name: django-config
data:
  REDIS_HOST: redis
  REDIS_PORT: "6379"
  CASSANDRA_HOST: cassandra.default.svc.cluster.local
  CASSANDRA_USER: "cassandra"
  CASSANDRA_PASSWORD: "cassandra"
