#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

python << END

import socket
import time
import argparse


service_name = "Cassandra"
port = 9042
ip = "cassandra"
timeout = 3

while True:
    sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    result = sock.connect_ex((ip, port))
    if result == 0:
        print("{0} port is now available.".format(service_name))
        break
    else:
        print("{0} port is not open. Will check again in 3 seconds...".format(service_name))
        time.sleep(timeout)
END
>&2 echo 'Running start script...'

exec "$@"
